version: 2.1

jobs:
  deploy_cloudformation:
    working_directory: ~/infrastructure
    docker: 
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run: chmod u+x setup.sh
      - run: ./setup.sh

workflows:
  pipeline:
    jobs:
      - deploy_cloudformation
