version: 2.1

jobs:
  deploy_cloudformation:
    working_directory: ~/infrastructure
    docker: 
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run: mkdir ~/.aws
      - run: echo "[default]" >> ~/.aws/credentials
      - run: echo "aws_access_key_id=$aws_access_key_id" >> ~/.aws/credentials
      - run: echo "aws_secret_access_key=$aws_secret_access_key" >> ~/.aws/credentials
      - run: cat ~/.aws/credentials
      - run: yum install sudo -y
      - run: chmod u+x setup.sh
      - run: ./setup.sh

workflows:
  pipeline:
    jobs:
      - deploy_cloudformation
