version: 2.1

jobs:
  deploy_cloudformation: 
    docker: 
      - image: amazon/aws-cli
    steps:
      - run: mkdir ~/.aws
      - run: echo "[default]" >> ~/.aws/credentials
      - run: echo "aws_access_key_id=$aws_access_key_id" >> ~/.aws/credentials
      - run: echo "aws_secret_access_key=$aws_secret_access_key" >> ~/.aws/credentials
      - run: ./setup.sh

workflows:
  welcome:
    jobs:
      - deploy_cloudformation
