---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes 
    upgrade: 'yes'

- name: "install node"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: true

- name: install pm2
  become: yes
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present     

- name: create folder for data 
  become: true 
  shell: mkdir -p /home/ubuntu/data 

- name: give write permissions 
  become: true 
  shell: chmod -R 775 /home/ubuntu/data  

- name: install index page
  become: true
  copy:
    src: index.js
    dest: /home/ubuntu/data/index.js
    backup: yes

- name: run server
  become: true
  shell: pm2 start /home/ubuntu/data/index.js